include *.mk


# Combined target to install fonts and configure terminals
configure-all: install-fonts configure-vscode configure-gnome-terminal
	@echo "All fonts installed and terminals configured successfully!"